/* video modes */
#define bw40				0
#define co40				1
#define bw80				2
#define co80				3
#define lores_4CO			4
#define lores_BW			5
#define lores_2CO			6
#define mono				7
#define pcjr_lores			8
#define pcjr_midres			9
#define pcjr_hires			10
#define ega_lores_16co		13
#define ega_hires_16co		14
#define ega_hires_bw		15
#define ega_hires_64co		16

/* video card base addresses */
#define EGA_CGA_ADDRESS		0xB8000000L
#define MDA_ADDRESS			0xB0000000L
