/* error codes */
#define OK								0
#define BAD_WDW_HANDLE					-1
#define BAD_TILE_HANDLE					-2
#define BAD_PARAMS						-3
#define NULL_POINTER					-4
#define DMA_ONLY						-5
#define NO_ACTIVE_WDW					-6
#define NO_ACTIVE_TILE					-7
#define OUT_OF_MEMORY					-8
#define CANT_CLOSE_LAST_TILE			-9
#define MAXIMUM_WINDOWS					-10
#define MAXIMUM_TILES					-11
#define NO_SPACE						-12
#define NOT_DONE						-100
#define MODIFIED                        -101

